### ISSUE TITLE
Resolution issue on Apple TV 4K

### ISSUE THREAD

**Issue by nreis11** [ckosmic/sm64ex-ios#17]
**Describe the bug**
The game only occupies 1/4 of the screen on  a 4K tV.

**To Reproduce**
1. Build using Xcode (using sm64tvos)
2. Run on Apple TV.
3. Stop product.
4. Launch the newly installed app on the Apple TV.

**Expected behavior**
Game displays full screen.

**Screenshots**
![Screen Shot 2021-11-16 at 5 34 06 PM](https://user-images.githubusercontent.com/19804045/142109875-0bd8b3af-4516-449e-8f06-069f660ff546.png)
![Screen Shot 2021-11-16 at 6 00 38 PM](https://user-images.githubusercontent.com/19804045/142109050-12902b85-e9e0-4961-acab-321a22e9c2fa.png)

**Additional context**
The Apple TV is the 4K (2021) model. Worth noting, on initial run, the game displays full screen. Only on subsequent launches from the app icon does the screen change to 1/4 size. This is my first time building and running an Apple TV app from Xcode, so forgive me if I did something wrong.

**Comment by ckosmic** [comment]
Thanks, I actually didn’t get a chance to test it on the ATV 4K so I thought at least something would be off on the 4K.  I’ll take a look at this.

**Comment by mannyd209** [comment]
> Thanks, I actually didn’t get a chance to test it on the ATV 4K so I thought at least something would be off on the 4K. I’ll take a look at this.

I have this same issue and also I can't do anything with my remote, I have the new remote with the power button and mute buttons. Not sure if there is gaming controller compatibility or if that is coming in the future? Thanks for the great work.

**Comment by ckosmic** [comment]
> I can't do anything with my remote, I have the new remote with the power button and mute buttons. Not sure if there is gaming controller compatibility or if that is coming in the future? Thanks for the great work.

Right now there is only support for game controllers to control the game itself.  The only functionality the remote has is pressing the play/pause button to bring up the menu and to exit the game

**Comment by sidshekar** [comment]
Can confirm the bug with 4kTV. The build initially runs full screen, but when you swap to an another app and change back to the game the framebuffer resizes t0 1080p.

**Comment by sidshekar** [comment]
I tried connecting my Xbox one as well as the DualSense controller. I was able to connect to the Apple 4kTV but the game doesn't respond to start, button clicks, etc. Basically the game is completely unresponsive  to controller. Maybe another Apple 4K TV bug?

Created a new issue for it.

**Comment by ckosmic** [comment]
This should now be fixed in 8f63446.  I tested it on an ATV 4K simulator and it seemed to fix the issue, but can you confirm it on actual hardware?  Thanks.

**Comment by sidshekar** [comment]
Ya I can confirm that the controller and the display issues are fixed on the Apple 4KTV. Although the icon I think scales up from the top left instead of the center so it looks weirdly scaled when selected. But that is a nit pick really. Haven't tested the game completely yet. But looks and plays fine from the 5 or so mins I played :D.

**Comment by nreis11** [comment]
Can confirm what @sidshekar said. During the 10 minutes that I played it, there were no issues. Only the minor app icon issue remains. Thanks for the fix!

**Comment by ckosmic** [comment]
ATV 4K app icons have been fixed in 3494da1
